In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


price = m1 * area + m2 * bedrooms + m3 * age + b
- features  = area, bedrooms,age
- coefficents = m1,m2,m3
- b = intercept

In [2]:
df = pd.read_csv('C:/Users/Ritik/Documents/home price mult.csv')

In [3]:
df

area  bedrooms  age  price  Unnamed: 4
0   NaN      2600  3.0     20      550000
1   NaN      3000  4.0     15      565000
2   NaN      3200  NaN     18      610000
3   NaN      3600  3.0     30      595000
4   NaN      4000  5.0      8      760000
5   NaN      4100  6.0      8      810000

In [ ]:
pd.DataFrame

In [4]:
df

area  bedrooms  age  price  Unnamed: 4
0   NaN      2600  3.0     20      550000
1   NaN      3000  4.0     15      565000
2   NaN      3200  NaN     18      610000
3   NaN      3600  3.0     30      595000
4   NaN      4000  5.0      8      760000
5   NaN      4100  6.0      8      810000

In [15]:
df1 = df.drop('area',axis=1)

In [16]:
df1

bedrooms  age  price  Unnamed: 4
0      2600  3.0     20      550000
1      3000  4.0     15      565000
2      3200  NaN     18      610000
3      3600  3.0     30      595000
4      4000  5.0      8      760000
5      4100  6.0      8      810000

In [17]:
# df = pandas.read_csv('C:/JIRA Excel File.csv')
# df.rename(columns=({'Custom field (Implemented Date)':'Custom field (Verified Date)'}))
# df.set_index('Custom field (Verified Date)').to_csv("C:/JIRA Excel File/Done.csv", index=None

In [18]:
df1.rename(columns=({'bedrooms':'area'}))


area  age  price  Unnamed: 4
0  2600  3.0     20      550000
1  3000  4.0     15      565000
2  3200  NaN     18      610000
3  3600  3.0     30      595000
4  4000  5.0      8      760000
5  4100  6.0      8      810000

In [19]:
df2=df1.rename(columns=({'bedrooms':'area','price':'age','age':'bedrooms','Unnamed: 4':'price'}))

In [20]:
df2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

bedrooms  age  price  Unnamed: 4
0      2600  3.0     20      550000
1      3000  4.0     15      565000
2      3200  NaN     18      610000
3      3600  3.0     30      595000
4      4000  5.0      8      760000
5      4100  6.0      8      810000

In [21]:
import math
median_bathrooms = math.floor(df2.bedrooms.median())
median_bathrooms

4

In [22]:
df2.bedrooms=df2.bedrooms.fillna(median_bathrooms)

In [46]:
df2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [47]:
from sklearn.linear_model import LinearRegression

In [42]:
reg = LinearRegression()

In [43]:
reg.fit(df2[['area','bedrooms','age']],df2.price)

LinearRegression()

In [44]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [45]:
reg.intercept_

221323.0018654043

In [52]:
df2

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [51]:
reg.predict(df2[['area','bedrooms','age']])

array([518217.63297611, 602590.07937407, 615307.4140366 , 597962.89583192,
       760663.42675457, 795258.55102673])

In [49]:
reg.predict([[3000,3,15]])

array([579201.19929613])

In [50]:
reg.predict([[2500,4,20]])

array([530400.26885984])

### Exercise solution 

In [53]:
data = pd.read_excel('C:/Users/Ritik/Documents/salary predi.xlsx')
data

experience test_score(out of 10)  interview_score(out of 10)  salary($)  \
0         NaN                   NaN                         8.0          9   
1         NaN                   NaN                         8.0          6   
2         NaN                  five                         6.0          7   
3         NaN                   two                        10.0         10   
4         NaN                 seven                         9.0          6   
5         NaN                 three                         7.0         10   
6         NaN                   ten                         NaN          7   
7         NaN                eleven                         7.0          8   

   Unnamed: 4  
0       50000  
1       45000  
2       60000  
3       65000  
4       70000  
5       62000  
6       72000  
7       80000

In [54]:
data = data.drop('experience',axis=1)
data

test_score(out of 10)  interview_score(out of 10)  salary($)  Unnamed: 4
0                   NaN                         8.0          9       50000
1                   NaN                         8.0          6       45000
2                  five                         6.0          7       60000
3                   two                        10.0         10       65000
4                 seven                         9.0          6       70000
5                 three                         7.0         10       62000
6                   ten                         NaN          7       72000
7                eleven                         7.0          8       80000

In [55]:
data1=data.rename(columns=({'test_score(out of 10)':'experience','interview_score(out of 10)':'test_score(out of 10)','salary($)':'interview_score(out of 10)','Unnamed: 4':'salary($)'}))

In [56]:
data1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [57]:
# df2.bedrooms=df2.bedrooms.fillna(median_bathrooms)
data1.experience = data1.experience.fillna('zero')

In [58]:
data2=data1.rename(columns=({'test_score(out of 10)':'test_score(0-10)'}))
data2

experience  test_score(0-10)  interview_score(out of 10)  salary($)
0       zero               8.0                           9      50000
1       zero               8.0                           6      45000
2       five               6.0                           7      60000
3        two              10.0                          10      65000
4      seven               9.0                           6      70000
5      three               7.0                          10      62000
6        ten               NaN                           7      72000
7     eleven               7.0                           8      80000

In [ ]:
x1=0

In [ ]:
filled_data1 = data2['test_score(0-10)'].fillna(x1)
data2['test_score(0-10)'] = filled_data1

In [ ]:
data2

In [48]:
numpy?

Object `numpy` not found.


In [ ]:
# data2.experience = data2.experience.apply(w2n.word_to_num)
from word2number import w2n
data2.experience = data2.experience.apply(w2n.word_to_num)

In [ ]:
data2


In [ ]:
# pip install word2number


In [2]:
# string = 'five, seven, six'
# num_list = [int(num.strip()) for num in string.split(',')]
# print(num_list)
# list = []
# for i in k:
#     print(i)
#     list.append(i)
# print(list)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()


In [ ]:
data2.columns

In [ ]:
model.fit(data2[['experience', 'test_score(0-10)', 'interview_score(out of 10)']],data2['salary($)'])


In [ ]:
model.predict([[0,7,8]])

In [ ]:
# filled_data = data2['test_score'].fillna(x)

# # update the 'test_score' column with the filled data
# data2['test_score'] = filled_data

In [ ]:
# def my_function():
#     return 42

# my_function() = 100
# # my_function() 
# def my_function():
#     return 42

# result = my_function()

In [ ]:
result

### Save file in python

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(reg,file)

In [ ]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)
    

In [ ]:
from sklearn.externals import joblib


In [ ]:
mp.coef_

In [ ]:
# import pandas as pd

# # create a sample DataFrame
# data2 = pd.DataFrame({'test_score': [1, 2, 3, 4, 5, 6, 7, 8, 9, None]})

# # fill missing values in the 'test_score' column with 10
# x = 10
# filled_data = data2['test_score'].fillna(x)

# # update the 'test_score' column with the filled data
# data2['test_score'] = filled_data

# # print the updated DataFrame
# print(data2)

In [34]:
import pandas as pd
x = {'marks':[20,22,44,55,77,'riri',89]}
x1 = pd.DataFrame(x)

In [35]:
x1

marks
0    20
1    22
2    44
3    55
4    77
5  riri
6    89

In [28]:
import math

In [29]:
import numpy as np

In [12]:
sum(x['marks'][0:4])

141

In [13]:
141+89

230

In [14]:
230/7

32.857142857142854

In [31]:
x1.isnull().sum()

marks    0
dtype: int64

In [32]:
x2 = x1['marks'].fillna(32.857)

In [36]:
x2 = x1['marks'].replace('riri',32.857)

In [44]:
x1['marks'] = x2

In [45]:
x1

marks
0  20.000
1  22.000
2  44.000
3  55.000
4  77.000
5  32.857
6  89.000

In [46]:
x1.rename(columns=({'marks':'score'}))

score
0  20.000
1  22.000
2  44.000
3  55.000
4  77.000
5  32.857
6  89.000